version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: jihunsns
    ports:
      - "6000:5432" # 외부 접근 허용
    environment:
      POSTGRES_USER: yangjihun
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
